import graphviz

dot = graphviz.Digraph("Booking_Flow", filename="diagram5_booking_flowchart", format="png")
dot.attr(rankdir="TB", bgcolor="white", fontsize="12", pad="0.4")
dot.attr("node", fontsize="11")

dot.node("start",     "Start",                          shape="oval",    style="filled", fillcolor="#2E86C1", fontcolor="white")
dot.node("login",     "Patient Logged In?",             shape="diamond", style="filled", fillcolor="#FCF3CF")
dot.node("goLogin",   "Redirect to Login",              shape="box",     style="filled", fillcolor="#FADBD8")
dot.node("openBook",  "Open Book Appointment Page",     shape="box",     style="filled", fillcolor="#D6EAF8")
dot.node("pickSpec",  "Select Specialty",               shape="box",     style="filled", fillcolor="#D6EAF8")
dot.node("loadDocs",  "Fetch Doctors by Specialty",     shape="box",     style="filled", fillcolor="#D6EAF8")
dot.node("pickDoc",   "Select Doctor",                  shape="box",     style="filled", fillcolor="#D6EAF8")
dot.node("pickDate",  "Select Appointment Date",        shape="box",     style="filled", fillcolor="#D6EAF8")
dot.node("confirm",   "Click Confirm Booking",          shape="box",     style="filled", fillcolor="#D6EAF8")
dot.node("dbInsert",  "INSERT INTO appointment\n(pid, docid, date, status=BOOKED)", shape="box", style="filled", fillcolor="#D5F5E3")
dot.node("success",   "Show: Booking Confirmed ✅",     shape="box",     style="filled", fillcolor="#D5F5E3")
dot.node("viewBook",  "View in My Bookings",            shape="box",     style="filled", fillcolor="#D6EAF8")
dot.node("end",       "End",                            shape="oval",    style="filled", fillcolor="#2E86C1", fontcolor="white")

dot.edge("start",    "login")
dot.edge("login",    "openBook", label="Yes", color="#117A65")
dot.edge("login",    "goLogin",  label="No",  color="#E74C3C")
dot.edge("goLogin",  "end")
dot.edge("openBook", "pickSpec")
dot.edge("pickSpec", "loadDocs")
dot.edge("loadDocs", "pickDoc")
dot.edge("pickDoc",  "pickDate")
dot.edge("pickDate", "confirm")
dot.edge("confirm",  "dbInsert")
dot.edge("dbInsert", "success")
dot.edge("success",  "viewBook")
dot.edge("viewBook", "end")

dot.render(cleanup=True)
print("✅ Booking Flowchart saved: diagram5_booking_flowchart.png")